spring:
  application:
    name: api-bridge
  datasource:
    url: jdbc:mysql://192.168.137.10:3306/api_bridge?useSSL=false&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://192.168.80.100:3306/api_bridge?useSSL=false&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false